#! /bin/bash

java -classpath ../../lib\;.. RTreeLoad mix tree 20 intersection > res
java -classpath ../../lib\;.. Exhaustive mix intersection > res2
sort -n res > a
sort -n res2 > b
if diff a b
then echo "Same results with exhaustive search. Everything seems fine."
else echo "PROBLEM! We got different results from exhaustive search!"
fi
rm -rf a b res res2 tree.*

